FutureCode0901/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),

    path('magazine/', include('magazine.urls')),

]

library/urls.py
from  django.urls import path, include
from . import views as v

urlpatterns = [
    path('index/', v.home),
    path('books/', v.all_books),
    path('books/<int:id>/', v.id_book),
    path('books/<str:name>/', v.name_book),
    path('', v.info),
    path('query/books/', v.get_all_book),
    path('query/books/<int:id>/', v.get_one_book),
    path('query/books/one-filter/', v.get_one_filter_book),
    path('query/books/more-filter/', v.get_more_filter_book),
    path('query/books/one-by-one-filter/', v.get_one_by_one_filter_book),
    path('query/books/create_blank/', v.create_blank_book),
    path('query/books/create/', v.create_book),
    path('query/books/create_user_book/', v.create_user_book),
    path('query/books/update/<int:id>/', v.update_book),
    path('query/books/delete/<int:id>/', v.delete_book),




]

magazine/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('index/',home, name='home_page' ),
    path('suppliers/', supplier_list, name='catalog_supplier_page'),
    path('suppliers/details/<int:id>/', supplier_details, name='details_supplier_page'),
    path('suppliers/create/', supplier_create, name='create_supplier_page'),
    path('product/', product_list, name='catalog_product_page'),


]

magazine/models.py
from django.db import models



MAX_LENGTH_CHAR = 255

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название компании')
    agent_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес поставщика')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'



class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name='Дата поставки')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Продукты')

    def __str__(self):
        return f'#{self.pk} - {self.data_supply} {self.supplier.name}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'



class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристика'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name =  'Тег'
        verbose_name_plural = 'Теги'


class Order(models.Model):
    MAGAZINE = "MG"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (MAGAZINE, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи"),
    ]
    FIO_customer = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='ФИО покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Комментарий')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=MAGAZINE, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершенияя заказа')

    books = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def __str__(self):
        return f'{self.pk} {self.FIO_customer} {self.date_create}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название товара')
    description = models.TextField(null=True, blank=True, verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Фотография товара')
    exists = models.BooleanField(default=True, verbose_name='В наличии?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')

    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Позиция характеристики'
        verbose_name_plural = 'Позиции характеристик'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    supply = models.ForeignKey(Supply,on_delete=models.PROTECT, verbose_name='Поставка' )

    count = models.PositiveIntegerField(verbose_name='Количество продукта')

    def __str__(self):
        return f'{self.product.name} - #{self.supply.pk}'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'

class Pos_order(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Продукт')
    order = models.ForeignKey('Order', on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество продукта')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка продукта')

    def __str__(self):
        return f"{self.pk} {self.product.name} {self.order.FIO_customer}"

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'

magazine/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'agent_firstname',
            'agent_name',
            'agent_patronymic',
            'agent_telephone',
            'address',
        )
    def clean_agent_telephone(self):
        agent_telephone = self.cleaned_data['agent_telephone']
        if re.match(r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}', agent_telephone):
            return agent_telephone
        raise ValidationError('Телефон не соответствует шаблону')


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = (
            'data_supply',
            'supplier',
        )

class Pos_supplyForm(forms.ModelForm):
    class Meta:
        model = Pos_supply
        fields = (
            'product',
            'supply',
            'count',
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = (
            'name',
            'description',
        )
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description',
        )
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'FIO_customer',
            'delivery_address',
            'delivery_type',
            'date_finish'
        )

magazine/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib import messages

# Create your views here.
def home(request):
    return render(request, 'magazine/index.html')

def supplier_list(request):
    list_supplier = Supplier.objects.filter(is_exists=True)
    context = {
        'list_sup': list_supplier
    }
    return render(request, 'magazine/supplier/catalog.html', context)

def supplier_details(request, id):
    supplier = get_object_or_404(Supplier, pk = id)

    context = {
        'supplier_object': supplier
    }
    return render(request, 'magazine/supplier/details.html', context)
def supplier_create(request):
    if request.method == "POST":
        form_supplier = SupplierForm(request.POST)
        if form_supplier.is_valid():
            new_supplier = Supplier(**form_supplier.cleaned_data)
            new_supplier.save()
            messages.success(request, 'Поставщик успешно добавлен')
            return redirect('catalog_supplier_page')
        messages.error(request, 'Неверно заполнены поля')
    else:
        form_supplier = SupplierForm()
    context = {
        'form': form_supplier
    }
    return render(request, 'magazine/supplier/create.html', context)

def product_list(request):
    list_product = Product.objects.filter(exists=True)
    context = {
        'list_product': list_product
    }
    return render(request, 'magazine/product/catalog.html', context)

magazine/templates/magazine/supplier/catalog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поставщики</title>
</head>
<body>
    <h1>Поставщики</h1>
    <a href="{% url 'home_page' %}">Вернуться на домашнюю страницу</a>
    {% if messages %}
        <h1>Оповещение</h1>
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div>
        <a href="{% url 'create_supplier_page' %}">Добавить поставщика</a>
    </div>
     <div>
         {% for supplier in list_sup %}

         <h1>{{ supplier.name }}</h1>
         <div>
             <p>
                 Фамилия: {{ supplier.agent_firstname }}
                 Имя: {{ supplier.agent_name }}
                 Отчество: {{ supplier.agent_patronymic }}
                 Телефон: {{ supplier.agent_telephone }}
                 Адрес: {{ supplier.address }}
             </p>
            <p>
                <a href="{% url 'details_supplier_page' supplier.pk %}">Подробнее...</a>
            </p>
         </div>
              -------------------------------------------------------------------
         {% endfor %}
     </div>

</body>
</html>

magazine/templates/magazine/supplier/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание поставщика</title>
</head>
<body>
    <h1>Создание поставщика</h1>
    {% if messages %}
        <h1>Оповещение</h1>
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
        <button type="submit">Создать поставщика</button>
    </form>
</body>
</html>

magazine/templates/magazine/supplier/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ supplier_object.name }}</title>
</head>
<body>
    <h1>Название поставщика: {{ supplier_object.name }}</h1>
______________________________________________________________________________
    <h3>
        Все поставки данного поставщика
    </h3>
       {% for supply in  supplier_object.supply_set.all%}
        <h3>Дата поставки: {{ supply.data_supply}}</h3>
        {% for postavka in supply.pos_supply_set.all %}
            <ul>
                <li>
                    Компонент поставки: {{ postavka.product.name }} - {{ postavka.count }} шт.
                </li>
            </ul>
        {% endfor %}
    {% endfor %}
</body>
</html>